version: '3.3'

services:
  db-node-1:
    build:
      context: mysql
      dockerfile: Dockerfile
    container_name: db-node-1
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: test
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    networks:
      - my-network
    ports:
      - 3360:3306
    volumes:
      - db-node-1-data:/var/lib/mysql

  db-node-2:
    build:
      context: mysql
      dockerfile: Dockerfile
    container_name: db-node-2
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: test
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    networks:
      - my-network
    ports:
      - 3361:3306
    volumes:
      - db-node-2-data:/var/lib/mysql
      
  proxysql:
    build:
      context: proxysql
      dockerfile: Dockerfile
    container_name: proxysql
    depends_on:
      - "db-node-1"
      - "db-node-2"
    volumes:
      - proxysql-data:/var/lib/proxysql
    networks:
      - my-network
    ports:
      # Mysql Client Port
      - "6033:6033"
      # Mysql Admin Port
      - "6032:6032"

  cache:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning 
    volumes: 
      - cache:/data

volumes:
  db-node-1-data:
  db-node-2-data:
  proxysql-data:
  cache:
    driver: local

networks:
  my-network:
    driver: "bridge"
    external: false